services:
    service-a:
        build:
            context: ./serviceA
            dockerfile: Dockerfile
        container_name: service-a
        ports:
            - "8080:8080"
        depends_on:
            - service-b
            - otel-collector
            - zipkin
        environment:
            - SERVICE_B_URL=http://service-b:8080
            - OTEL_SERVICE_NAME=service-a
            - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
        networks:
            - zipcode-temperature-tracing

    service-b:
        build:
            context: ./serviceB
            dockerfile: Dockerfile
        container_name: service-b
        ports:
            - "8081:8080"
        depends_on:
            - otel-collector
            - zipkin
        environment:
            - API_KEY=${WEATHER_API_KEY}
            - OTEL_SERVICE_NAME=service-b
            - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
        networks:
            - zipcode-temperature-tracing

    otel-collector:
        image: otel/opentelemetry-collector:latest
        command: [ "--config=/etc/otel-collector-config.yaml" ]
        volumes:
            - ./config/otel/config.yaml:/etc/otel-collector-config.yaml:ro
        ports:
            - "4318:4318"
            - "4317:4317"
        networks:
            - zipcode-temperature-tracing

    zipkin:
        image: openzipkin/zipkin
        ports:
            - "9411:9411"
        depends_on:
            - otel-collector
        networks:
            - zipcode-temperature-tracing

networks:
    zipcode-temperature-tracing:
        driver: bridge
